### ISSUE TITLE
[BUG] import RegularSynthesizer does not work in with ydata-synthetic version 2.0.0

### ISSUE THREAD

**Issue by ednaruiz** [ydataai/ydata-synthetic#352]
**Describe the bug**

RegualSynthesizer does not seem to exist anymore in the latest release

**To Reproduce**
1. Install ydata-synthetic throug pip 
2. Try to export: from ydata_synthetic.synthesizers.regular import RegularSynthesizer (note this is the export indicated in the notebooks of the example directory 
3. See error:
```
>>> from ydata_synthetic.synthesizers.regular import RegularSynthesizer
<stdin>:1: DeprecationWarning: `import ydata_synthetic.synthesizers` is deprecated. Please use `import ydata.sdk.synthesizers` instead.For more information check https://docs.synthetic.ydata.ai/latest and https://docs.fabric.ydata.ai/latest/sdk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'RegularSynthesizer' from 'ydata_synthetic.synthesizers.regular'
```

**Desktop (please complete the following information):**
 - OS: google Colab
- python 3.9 

**Additional context**
A quick look at the available classes provides:

```
>>> import ydata_synthetic.synthesizers.regular as reg
>>> print(dir(reg))
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'cgan', 'cramergan', 'ctgan', 'cwgangp', 'dragan', 'gmm', 'vanillagan', 'warn', 'wgan', 'wgangp']
```
